config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :profiles
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles, only: [:index, :show, :edit, :update]
  resources :appointments, only: [:index, :show, :edit, :update, :new, :create]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  phone_number           :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_type              :string           not null
#  user_id                :bigint           not null
#
class Profile < ApplicationRecord
  USER_TYPES = %i[user doctor].freeze
  PUBLIC_ATTRIBUTES = %w[email phone_number].freeze

  PUBLIC_ATTRIBUTES_MAPPER = {
    'user' => User::PUBLIC_ATTRIBUTES,
    'doctor' => Doctor::PUBLIC_ATTRIBUTES
  }.freeze

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  belongs_to :user, polymorphic: true, dependent: :destroy, optional: false, autosave: true
  accepts_nested_attributes_for :user

  validates :phone_number, presence: true,
                           uniqueness: true,
                           numericality: true,
                           length: { minimum: 10, maximum: 15 }

  scope :doctors, -> { where(user_type: 'Doctor') }
  scope :users, -> { where(user_type: 'User') }

  def user?
    user_type == 'User'
  end

  def doctor?
    user_type == 'Doctor'
  end

  def user_attributes=(attributes)
    return unless USER_TYPES.include?(user_type.underscore.to_sym)

    self.user ||= user_type.constantize.new
    self.user.assign_attributes(attributes)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource

  before_action :set_profile, only: %i[show edit update]
  before_action :set_scope, only: %i[index]

  PROFILE_LOADER_MAPPER = {
    'doctor' => Profiles::LoadDoctorProfiles,
    'user' => Profiles::LoadUserProfiles
  }.freeze

  def index
    @profiles = PROFILE_LOADER_MAPPER[@scope].perform(filter_params)
  end

  def show
    session[:doctor_id] = @profile.user.id if @profile.doctor?
  end

  def edit
    authorize! :edit, @profile
  end

  def update
    authorize! :update, @profile
    if @profile.update(profile_params)
      flash[:success] = 'Profile was successfully updated!'
      redirect_to @profile
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def set_scope
    @scope = params[:scope] || 'doctor'
  end

  def filter_params
    params.require(:filters).permit(Profiles::LoadDoctorProfiles::DOCTOR_FILTERS)
  rescue ActionController::ParameterMissing
    nil
  end

  def profile_params
    params.require(:profile).permit(
      :user_type, :email, :phone_number,
      user_attributes: Profile::PUBLIC_ATTRIBUTES_MAPPER[current_profile.user_type.downcase].map(&:to_sym)
    )
  end
end

app/views/profiles/edit.html.erb
<main class="form-edit">
  <%= render "devise/shared/error_messages", resource: @profile %>

  <%= form_for(@profile, as: :profile, url: profile_path(@profile), method: :patch) do |f| %>
    <h1 class="h3 mb-3 fw-normal">Edit</h1>

    <div class="form-floating">
      <%= f.email_field :email, class: 'form-control', autofocus: true, autocomplete: "email", placeholder: "example@mail.com"%>
      <%= f.label :email %>
    </div>

    <div class="form-floating">
      <%= f.phone_field :phone_number, class: 'form-control', autofocus: true, autocomplete: "phone", placeholder: "0999999999" %>
      <%= f.label :phone_number %>
    </div>

    <%= f.fields_for(:user_attributes, @profile.user.decorate, include_id: false) do |user_attributes_f| %>
      <% Profile::PUBLIC_ATTRIBUTES_MAPPER[current_profile.user_type.downcase].excluding('category').each do |attribute_name| %>
        <div class="form-floating">
          <%= user_attributes_f.text_field attribute_name.to_sym, class: 'form-control', autofocus: true, placeholder: attribute_name.humanize %>
          <%= user_attributes_f.label attribute_name.to_sym %>
        </div>
      <% end %>
    <% end %>

    <%= f.submit "Update", class: 'w-100 btn btn-lg btn-primary' %>
  <% end %>
  <%= link_to "Cancel", profile_path(@profile), method: :get %>
</main>

app/views/profiles/index.html.erb
<main class="profiles-section">

  <% if current_profile.user? %>
    <%= form_for(:filters, url: profiles_path, method: :get) do |f| %>
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, class: 'form-control' %>
      <%= f.submit "Filter", class: 'btn btn-primary' %>
    <% end %>
    <%= link_to "Clear filters", profiles_path(scope: 'doctor'), method: :get %>
  <% end %>

  <table class="table table-sm caption-top table-info table-striped">
    <caption>Available doctors</caption>
    <thead>
      <tr>
        <% Profile::PUBLIC_ATTRIBUTES_MAPPER[@scope].each do |attribute_name| %>
          <th scope="col"><%= attribute_name.humanize %></th>
        <% end %>
        <% Profile::PUBLIC_ATTRIBUTES.each do |attribute_name| %>
          <th scope="col"><%= attribute_name.humanize %></th>
        <% end %>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @profiles.each do |profile| %>
        <tr>
          <% profile.user.class.const_get(:PUBLIC_ATTRIBUTES).each do |attribute_name| %>
            <td><%= profile.user.decorate.public_send(attribute_name) %></td>
          <% end %>
          <% profile.class.const_get(:PUBLIC_ATTRIBUTES).each do |attribute_name| %>
            <td><%= profile.public_send(attribute_name) %></td>
          <% end %>
          <td><%= link_to 'Info', profile_path(profile), method: :get %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/profiles/show.html.erb
<main class="profile-section">
  <h2>Welcome <%= @profile.decorate.full_name %></h2>

  <table class="table table-sm caption-top table-info table-striped">
    <caption>
      <%= @profile.user_type %> details
      <% if can?(:edit, @profile) %>
        |
        <%= link_to "Edit", edit_profile_path(@profile), method: :get %>
      <% end %>
    </caption>
    <tbody>
    <% @profile.user.class.const_get(:PUBLIC_ATTRIBUTES).each do |attribute_name| %>
      <tr>
        <th scope="row"><%= attribute_name.humanize %></th>
        <td><%= @profile.user.decorate.public_send(attribute_name) %></td>
      </tr>
    <% end %>
    <% @profile.class.const_get(:PUBLIC_ATTRIBUTES).each do |attribute_name| %>
      <tr>
        <th scope="row"><%= attribute_name.humanize %></th>
        <td><%= @profile.decorate.public_send(attribute_name) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <% if current_profile.user? && @profile.doctor? %>
    <%= button_to "Create appointment", new_appointment_path, method: :get, class: 'btn btn-outline-success' %>
  <% end %>
</main>