config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :profiles
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles, only: [:index, :show, :edit, :update]
  resources :appointments, only: [:index, :show, :edit, :update, :new, :create]
end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id           :bigint           not null, primary key
#  user_id      :bigint           not null
#  doctor_id    :bigint           not null
#  status       :enum             default("planned"), not null
#  prescription :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor

  enum :status, { planned: 'planned', completed: 'completed' }

  validate :appointment_count_within_limit, on: :create

  private

  def appointment_count_within_limit
    return if doctor.appointments.planned.count < Doctor::APPOINTMENT_LIMIT

    errors.add(:base, 'This doctor is too busy')
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource

  before_action :set_appointment, only: %i[show edit update]

  def index
    @appointments = current_profile.user.appointments.order(:status)
  end

  def show; end

  def new
    @appointment = Appointment.new
    authorize! :new, @appointment
  end

  def edit
    authorize! :edit, @appointment
  end

  def create
    @appointment = Appointment.new(appointment_params)
    authorize! :create, @appointment
    if @appointment.save
      flash[:success] = 'Appointment was successfully created!'
      redirect_to @appointment
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @appointment
    if @appointment.update(update_appointment_params)
      @appointment.completed! if @appointment.prescription_previously_changed?
      flash[:success] = 'Appointment was successfully processed!'
      redirect_to @appointment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:user_id, :doctor_id)
  end

  def update_appointment_params
    params.require(:appointment).permit(:prescription)
  end
end

app/views/appointments/edit.html.erb
<main class="form-process-appointment">
  <%= render "devise/shared/error_messages", resource: @appointment %>

  <%= form_for(@appointment, as: :appointment, url: appointment_path(@appointment), method: :patch) do |f| %>
    <h1 class="h3 mb-3 fw-normal">Process appointment</h1>

    <div class="form-floating">
      <%= f.text_area :prescription, class: 'form-control', autofocus: true, placeholder: "prescription"%>
      <%= f.label :prescription %>
    </div>

    <%= f.submit "Process", class: 'w-100 btn btn-lg btn-primary' %>
  <% end %>
  <%= link_to "Cancel", appointment_path(@appointment), method: :get %>
</main>

app/views/appointments/index.html.erb
<main class="appointments-section">
  <table class="table table-sm caption-top table-info table-striped">
    <caption>Appointments</caption>
    <thead>
    <tr>
      <th scope="col">Doctor</th>
      <th scope="col">User</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td>
          <%= link_to appointment.doctor.profile.decorate.full_name, profile_path(appointment.doctor.profile), method: :get %>
        </td>
        <td>
          <%= link_to appointment.user.profile.decorate.full_name, profile_path(appointment.user.profile), method: :get %>
        </td>
        <td><%= appointment.status %></td>
        <td><%= link_to 'Info', appointment_path(appointment), method: :get %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</main>

app/views/appointments/new.html.erb
<main class="form-signup">
  <%= render "devise/shared/error_messages", resource: @appointment %>

  <%= form_for(@appointment, as: :appointment, url: appointments_path, method: :post) do |f| %>
    <%= f.hidden_field :user_id, value: current_profile.user.id %>
    <%= f.hidden_field :doctor_id, value: session[:doctor_id] %>
    <%= f.submit "Create appointment", class: 'btn btn-outline-success' %>
  <% end %>
</main>

app/views/appointments/show.html.erb
<main class="appointment-section">
  <table class="table table-sm caption-top table-info table-striped">
    <caption>Appointment details</caption>
    <tbody>
      <tr>
        <th scope="row">Doctor</th>
        <td>
          <%= link_to @appointment.doctor.profile.decorate.full_name, profile_path(@appointment.doctor.profile), method: :get %>
        </td>
      </tr>
      <tr>
        <th scope="row">User</th>
        <td><%= @appointment.user.profile.decorate.full_name %></td>
      </tr>
      <tr>
        <th scope="row">Status</th>
        <td><%= @appointment.status %></td>
      </tr>
      <tr>
        <th scope="row">Prescription</th>
        <td><%= @appointment.prescription %></td>
      </tr>
    </tbody>
  </table>

  <% if can?(:edit, @appointment) %>
    <%= button_to "Process appointment", edit_appointment_path(@appointment), method: :get, class: 'btn btn-outline-success' %>
  <% end %>
</main>