config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :profiles
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles, only: [:index, :show, :edit, :update]
  resources :appointments, only: [:index, :show, :edit, :update, :new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolyclinicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="notice alert alert-info fixed-top"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if profile_signed_in? %>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <%= link_to "Clinic APP", root_path, method: :get, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <%= link_to "Home", root_path, method: :get, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Profile", profile_path(current_profile), method: :get, class: 'nav-link' %>
              </li>
              <% if current_profile.user? %>
                <li class="nav-item">
                  <%= link_to "Doctors", profiles_path(scope: 'doctor'), method: :get, class: 'nav-link' %>
                </li>
              <% end %>
              <% if current_profile.doctor? %>
                <li class="nav-item">
                  <%= link_to "Users", profiles_path(scope: 'user'), method: :get, class: 'nav-link' %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to "Appointments", appointments_path, method: :get, class: 'nav-link' %>
              </li>
            </ul>
            <span class="navbar-text me-2">
              <%= current_profile.email %>
            </span>
            <div class="d-flex">
              <%= button_to "Sign out", destroy_profile_session_path, method: :delete, class: 'btn btn-outline-danger' %>
            </div>
          </div>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>